### ISSUE TITLE
Replace firstRoute component and render again from HelloPage component

### ISSUE THREAD

**Issue by timdoes** [t4t5/react-native-router#10]
Is there a way to replace the firstRoute{component} from the current component view?

For example in your basic example, there is a HelloPage component. Is there a way that there could be a button there to change the `<Router />` firstRoute prop's value and render the component again. This would create a new root view.

Thanks,
-Tim

**Comment by t4t5** [comment]
I haven't tested this so there might be some syntax errors, but I think the concept should work. :P Let's say the firstRoute-view looks like this:

```javascript
var myView = React.createClass({
  changeText: function() {
    this.props.customAction();
  },

  render: function() {
    return (
      <View>
        <Text>Hello {this.props.data.something}!</Text>
        <TouchableOpacity onPress={changeText}>
          <Text>Click to change the text!</Text>
        </TouchableOpacity>
     </View>
    );
  }
});
```

... and the view containing your router looks like this:

```javascript
var myApp = React.createClass({
  getInitialState: function() {
    return {
      textInView: "world"
    };
  },

  changeStuff: function() {
    this.setState({
      textInView: "planet earth!"
    });
  },

  render: function() {
    myRoute = {
      name: "My first view",
      component: myView,
      data: {
        something: this.state.textInView
      }
    };

    return <Router firstRoute={myRoute} customAction={this.changeStuff} />
  }
});
```

So short answer: use `this.props.customAction` (and preferably pass in a string as a key in case you have multiple actions). Let me know if this works!

**Comment by timdoes** [comment]
In this example, it gives an error:

message: undefined is not a function (evaluating 'this.props.customAction()')"

**Comment by t4t5** [comment]
Sorry, I forgot that customActions aren't set in the route views but in the navigation bar. I added this in v0.1.3.

I used this code now to try to achieve what you asked for:
```javascript
var MyView = React.createClass({
  changeText: function() {
    this.props.customAction();
  },

  render: function() {
    return (
      <View>
        <Text>Hello world!</Text>
        <TouchableOpacity onPress={this.changeText}>
          <Text>Click to change the text!</Text>
        </TouchableOpacity>
      </View>
    );
  }
});

var MyOtherView = React.createClass({
  render: function() {
    return (
      <View>
        <Text>I changed!</Text>
      </View>
    );
  }
});

var MyApp = React.createClass({
  getInitialState: function() {
    return {
      currentRoute: {
        name: "My first view",
        component: MyView,
      }
    };
  },

  changeStuff: function() {
    this.setState({
      currentRoute: {
        name: "My other view",
        component: MyOtherView,
      }
    });
  },

  render: function() {

    console.log("rerender with" + this.state.currentRoute.name);

    return <Router firstRoute={this.state.currentRoute} customAction={this.changeStuff} />
  }
});
```

However, it seems like the Router doesn't rerender the firstRoute oddly enough, even though the state has changed. I wonder if it could have anything to do with this? https://github.com/facebook/react-native/issues/795

**Comment by timdoes** [comment]
Very simple flow. Was able to fix the issue by creating a separate `<Router />` object.

Thank you for all the help!!

**Comment by dimoreira** [comment]
Hey @timdoes.

Can you post your solution for this? I'm trying to use some kind of session (login) validation before attach the `currentRoute` to the `Router` and I can't manage to make it work. The first router attached to the Router cannot change.

Can you give any help @t4t5? Thanks in advance.

My example:

```javascript
var MyApp = React.createClass({
	getInitialState: function() {
		return {
			isLoggedIn: false,
			currentRoute: {
				name: 'FacebookConnectPage',
				component: FacebookConnectPage,
				titleComponent: LogoNavTitle
			}
		};
	},

	componentDidMount: function() {
		FacebookLoginManager.getCredentials(function(err, response) {
			if (err) {
				this.setState({
					isLoggedIn: false,
					currentRoute: {
						name: 'FacebookConnectPage',
						component: FacebookConnectPage,
						titleComponent: LogoNavTitle
					}
				});
			} else {
				this.setState({
					isLoggedIn: true,
					currentRoute: {
						name: 'ProjectInfoPage',
						component: ProjectInfoPage,
						titleComponent: LogoNavTitle
					}
				});
			}
		}.bind(this));
	},

  render: function() {
		return (
			<Router
				headerStyle={styles.header}
				titleStyle={styles.headerTitle}
				firstRoute={this.state.currentRoute}
			/>
		);
  }
});
```

**Comment by timdoes** [comment]
Hi @dimoreira,

I actually have started using McFly (Flux) for handing my routing. But here is how I'd do it with this example:

```
render: function() {
  if(this.state.isLoggedIn) {
    return <Router firstRoute={FacebookConnectPage} />
  } else {
    return <Router firstRoute={ProjectInfoPage} />
  }
}
```

**Comment by dimoreira** [comment]
Thanks @timdoes, but that didn't work for me either. :disappointed:
