### ISSUE TITLE
Issue with headerStyle / status bar style

### ISSUE THREAD

**Issue by yascov** [t4t5/react-native-router#18]
If we set the headerStyle to use the white color, the  status bar style does not change and therefore it's invisible.
![screen shot 2015-04-25 at 10 32 45 am](https://cloud.githubusercontent.com/assets/10214494/7332508/4433f3ec-eb3a-11e4-81b3-acb80c51cc80.png)

**Comment by t4t5** [comment]
Ah yes, the library automatically sets is to white. Will fix this in the next release! In the meantime, you can comment out the line that is responsible if it bugs you: https://github.com/t4t5/react-native-router/blob/master/index.js#L110
