### ISSUE TITLE
Use Router with hidden navigation bar?

### ISSUE THREAD

**Issue by jhopper28** [t4t5/react-native-router#19]
Is there any way to use the router functionality, but hide the navigation bar altogether? I'd like to do this on iPad with custom navigation controls, but none of the styles I set seems to have any such affect.

**Comment by josebalius** [comment]
+1 on this, really good use case are login pages. I may give it a shot this weekend by replacing the Navigation bar in the route with an empty view, i'll submit a PR if I get some progress.

**Comment by TylerYang** [comment]
+1

**Comment by t4t5** [comment]
Let me know how it goes @josebalius! Unfortunately I'm a little busy this week so I don't have time to fix this yet. It's on the roadmap!

**Comment by chris-alexander55** [comment]
1+

**Comment by nparsons08** [comment]
+1

**Comment by liubko** [comment]
+1
