### ISSUE TITLE
Expose Navigator SceneConfigs via route property?

### ISSUE THREAD

**Issue by sherbondy** [t4t5/react-native-router#2]
Heya, this is nice. Going to incorporate it into a project.

What do you think about exposing Navigator.SceneConfigs by adding, say, a sceneConfig property to routes?

Sometimes it is nice to push onto the route stack from the bottom instead of just left/right nav pushing. And no point making another Navigator instance when this library already wraps a Navigator.

Happy to send a pull req sometime this week if that sounds good.

**Comment by t4t5** [comment]
Hm. I've never seen a page appear from the bottom that keeps the same navigation bar in view (and for good reasons: the bottom-up animation should be reserved for modal-type behaviour). Is there anything else that you can do with SceneConfigs that would be nice to have (the documentation seems to be lacking a bit).

**Comment by sherbondy** [comment]
Yeah, good point. I think that's all SceneConfig offers for now. Gonna close this!

I guess there's a bit of an impedance mismatch from the current React Native notion of a Navigator and the Cocoa Touch notion of a UINavigationController. React Native Navigators seem general enough that you can largely stick with one Navigator for all routes, regardless of whether a route is presented as modal, whereas I'm guessing your goal with this project is to make something much closer to as seamless UINavigationController + the associated default GUI elements in React Native land. Sounds good!
