### ISSUE TITLE
backButtonComponent --> new `leftCorner`

### ISSUE THREAD

**Issue by samuelcouch** [t4t5/react-native-router#22]
I've been using react-native-router and one of the things I haven't been able to get working, is adding a component to the left corner (on the initial route) out of the box. Essentially I am trying to create a `leftCorner` option because it seems that `backButtonComponent` doesn't display unless there is something to go back to. The main use-case for this, is adding a menu option on the initial route.

**Comment by t4t5** [comment]
Hi @samuelcouch. Sorry for getting back so late.

This is actually already possible. Check the Twitter example (the first route has a `leftCorner`-key).

```javascript
var firstRoute = {
  name: 'Home',
  component: HomePage,
  leftCorner: AddPeople
};

var TwitterApp = React.createClass({
  render() {
    return (
      <Router 
        firstRoute={firstRoute} 
        headerStyle={styles.header}
        backButtonComponent={redSquare}
        leftCorner={redSquare}
      />
    )
  }
});
```
