### ISSUE TITLE
Question: How would you "bubble up" to the top from a grandchild element? e.g. TweetBig?

### ISSUE THREAD

**Issue by MossP** [t4t5/react-native-router#26]
Great Plugin. It looks, feels and works really well! :)

Apologies for what is probably a newbie question but I've been looking at your demo app and tried to add a link from the TweetBig page, to push another page to the stack. I do not seem to be able to pass the reference of myFunction from HomePage into TweetBig so i can "bubble up" to the top level.

I tried:
in HomePage.js:
```
goToTweet: function(tweetData){
    this.props.toRoute({
        name: "Tweet",
        component: <TweetPage myFunction={this.myFunction} />
        data: tweetData
    });
},

myFunction: function(){
    console.log("myFunctionCalled");
},
```

and also tried the following (also modifying TweetBig to accept the new structure):
```
goToTweet: function(tweetData){
    this.props.toRoute({
        name: "Tweet",
        component: TweetPage,
        data: {
            tweetData: tweetData,
            myFunction: {this.MyFunction}
        }
    });
},
```

I have tried swapping the myFunction line for:
```
myFunction: this.MyFunction
myFunction: myFunction
myFunction: this.myFunction()
```
and also moving it out of the data section to it's own element but nothing seems to work.

Any assistance is appreciated. :)

**Comment by MossP** [comment]
For anyone else with this issue:
I had been trying to achieve this because whenever I called a class that already existed in the stack I got the following error:
```
Invariant Violation: Expected a component class, got [object Object].
```
It appears this an error in cyclic dependancies. To get around this in the demo app I changed all of the 'requires' (except the main root elements to lazyload just before they are needed preventing the cyclic dependency.

E.g. instead of
```
var myClass = require('./MyClass');
...
(some other code)
...
render: function(){
    return(
        <TouchableHighlight onPress={ () => {this.props.toRoute( {name: "myPage", component: myClass, data: "SomeData" } )}>
            <Text>Link</Text>
        </TouchableHighlight>
    );
}
```
to
```
goToMyRoute: function(myParameter){
    var myClass = require('./MyClass');
    this.props.toRoute( {name: "myPage", component: myClass, data: myParameter })
}

render: function(){
    return(
        <TouchableHighlight onPress={ () => {this.goToMyRoute("SomeData")} }>
            <Text>Link</Text>
        </TouchableHighlight>
    );
}
```

I would still be interested to know how to "bubble up" but this might help someone else in a fix.

**Comment by MossP** [comment]
ok, so that's what {...props} does.

**Comment by mitchozer** [comment]
I struggled with the same issue for hours, thanks so much for following up with this!
