### ISSUE TITLE
Defining the name of a page

### ISSUE THREAD

**Issue by RWOverdijk** [t4t5/react-native-router#51]
I've been playing around with this module a bit and so far it works really well. There's one thing that's bothering me though.. That's the name property. It looks like it's up to the initiator of the view to decide what the name of the view should be. For instance, on line 45 of HomePage.js in the twitter example:

```javascript
{
  goToTweet: function(tweetData) {
    this.props.toRoute({
      name: "Tweet",
      component: TweetPage,
      data: tweetData
    });
  }
}
```

The name is being defined there. What if the app has several places that initiate this? Would I have to add this all over the place? Can it be defined from within the page view itself, too?

**Comment by allenhartwig** [comment]
You could accomplish this like so:
```js
{
  goToTweet: function(tweetData) {
    var TweetPage = require('./pages/tweet')';
    this.props.toRoute({
      name: TweetPage.title,
      component: TweetPage.component,
      data: tweetData
    });
  }
}
```
with pages/tweet.js exporting:
```js
module.exports = {
   title: 'Tweet',
   component: myTweetComponent
};
```

**Comment by allenhartwig** [comment]
Alternatively this works as well:
```js
{
  goToTweet: function(tweetData) {
    var TweetPage = require('./pages/tweet')';
    this.props.toRoute({
      name: TweetPage.displayName,
      component: TweetPage,
      data: tweetData
    });
  }
}
```

Just ensure you have the displayName property defined to your desired title on within your `React.createClass`.

**Comment by RWOverdijk** [comment]
Satisfying enough. Thanks.
