### ISSUE TITLE
cutomTitleComponent press to notify the current render scece to update

### ISSUE THREAD

**Issue by philonpang** [t4t5/react-native-router#7]
hi，if i want to press my custom titleComponent to notify current scene to update the view , how to implement this, do you have some idea? thanks

**Comment by t4t5** [comment]
Since version 0.1.2, you can call a custom action from your header components to notify your main view. Check out the release notes here, I think it should solve your problem: https://github.com/t4t5/react-native-router/releases/tag/v0.1.2
